### ISSUE TITLE
Got too many requests error. 

### ISSUE THREAD

**Issue by chirag127** [xenova/sponsorblock-ml#4]
I got too many requests error while training the model

**Comment by xenova** [comment]
To avoid getting such an error, you have to pass in a cookies file to the `list_transcripts` method (in preprocess.py).

Follow the steps here to download a cookies.txt file: https://github.com/jdepoix/youtube-transcript-api#cookies
Then change 
```python
def list_transcripts(video_id):
    try:
        return YouTubeTranscriptApi.list_transcripts(video_id)
    except json.decoder.JSONDecodeError:
        return None
```

to 
```python
def list_transcripts(video_id):
    try:
        return YouTubeTranscriptApi.list_transcripts(video_id, cookies="PATH/TO/COOKIES.TXT")
    except json.decoder.JSONDecodeError:
        return None

```

Let me know if that fixes it 👍  I didn't really expect anyone else to train the models... 😅

**Comment by chirag127** [comment]
Is there a way, I can disable the download of transcripts while running the model?

**Comment by xenova** [comment]
> Is there a way, I can disable the download of transcripts while running the model?

Ummm, what would you use the model for then? 😅 ... it needs transcripts to run? Unless you want to throw an error when a transcript is not found?

**Comment by chirag127** [comment]
> > Is there a way, I can disable the download of transcripts while running the model?
> 
> Ummm, what would you use the model for then? 😅 ... it needs transcripts to run? Unless you want to throw an error when a transcript is not found?

Well Ihad asked a wrong question it should be deleting the transcript after getword returned words.

**Comment by mrsangjunboon2018** [comment]
okay.
