### ISSUE TITLE
what is CouldNotRetrieveTranscript

### ISSUE THREAD

**Issue by chirag127** [xenova/sponsorblock-ml#5]
what is CouldNotRetrieveTranscript in https://github.com/xenova/sponsorblock-ml/blob/b7718d8aec235c625e396890981720ff39b2a60a/src/preprocess.py#L229 ? Is that the subtitle actually empty or you are just doing ? if the subtitle are not actually empty I will do speech recognition

**Comment by xenova** [comment]
It means that there was some problem getting the transcript using youtube_transcript_api (https://github.com/jdepoix/youtube-transcript-api). It's basically a catch-all for when some problem occurs. You can read more about it here: https://github.com/jdepoix/youtube-transcript-api/blob/master/youtube_transcript_api/_errors.py#L4

For all intents and purposes, it's the same as saying it doesn't have a transcript. So, doing speech recognition could work in place of it
